[profile.default]
src = "."
out = "out"
libs = ["lib"]
script = "script"
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
worldchain_mainnet = "https://worldchain-mainnet.g.alchemy.com/public"
worldchain_sepolia = "https://worldchain-sepolia.g.alchemy.com/public"

[etherscan]
worldchain_mainnet = { key = "${WORLDSCAN_API_KEY}", url = "https://api.worldscan.org/api" }
worldchain_sepolia = { key = "${WORLDSCAN_API_KEY}", url = "https://api-sepolia.worldscan.org/api" }
